export const cars = [
  {
    id: 1,
    manufacture_name: "maruthi",
    model_name: "suzuki",
    model_year: "2022",
    Vehicle_color: "red",
    Engine_number: "asdvs122232",
    chasis_number: "aasd232323",
    fuel_type: "Petrol",
    transmission: "Automatic",
    extra_fittings: "no",
    tax_valid: "2024-10-14",
    total_km_driven: "20000",
    vehicle_registration_number: "KL01cl8102",
    published: "yes",
    sold: "no",
    description: "good cars",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price: "32000000",
    thumbnail: "porschecar.png",
  },
  {
    id: 2,
    manufacture_name: "Toyota",
    model_name: "Camry",
    model_year: "2022",
    Vehicle_color: "white",
    Engine_number: "werw2321312",
    chasis_number: "dsadsa232323",
    fuel_type: "Petrol",
    transmission: "Automatic",
    extra_fittings: "yes",
    tax_valid: "2025-12-31",
    total_km_driven: "15000",
    vehicle_registration_number: "NY23AB1234",
    published: "yes",
    sold: "no",
    description: "Like-new Camry with low mileage",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price: "2800000",
    thumbnail: "porschecar.png",
  },
  {
    id: 3,
    manufacture_name: "Honda",
    model_name: "Civic",
    model_year: "2023",
    Vehicle_color: "blue",
    Engine_number: "asdad343434",
    chasis_number: "sdadsa323232",
    fuel_type: "Petrol",
    transmission: "Automatic",
    extra_fittings: "no",
    tax_valid: "2026-06-30",
    total_km_driven: "5000",
    vehicle_registration_number: "KA51AB5678",
    published: "yes",
    sold: "no",
    description: "Sleek and stylish Honda Civic",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price: "3200000",
    thumbnail: "porschecar.png",
  },
  {
    id: 4,
    manufacture_name: "Chevrolet",
    model_name: "Silverado",
    model_year: "2022",
    Vehicle_color: "red",
    Engine_number: "asdda3434",
    chasis_number: "sdsada23232",
    fuel_type: "Diesel",
    transmission: "Automatic",
    extra_fittings: "yes",
    tax_valid: "2025-11-15",
    total_km_driven: "10000",
    vehicle_registration_number: "TN01BC1234",
    published: "yes",
    sold: "no",
    description: "Powerful and versatile Chevy Silverado",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price: "4500000",
    thumbnail: "porschecar.png",
  },
  {
    id: 5,
    manufacture_name: "Nissan",
    model_name: "Altima",
    model_year: "2023",
    Vehicle_color: "silver",
    Engine_number: "sdaa232343",
    chasis_number: "dsadasd2323",
    fuel_type: "Petrol",
    transmission: "Manual",
    extra_fittings: "yes",
    tax_valid: "2026-05-20",
    total_km_driven: "8000",
    vehicle_registration_number: "MH02CD4567",
    published: "yes",
    sold: "no",
    description: "Luxury and comfort in the Nissan Altima",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price: "3800000",
    thumbnail: "porschecar.png",
  },
  {
    id: 6,
    manufacture_name: "Ford",
    model_name: "Mustang",
    model_year: "2021",
    Vehicle_color: "yellow",
    Engine_number: "asdd232123",
    chasis_number: "sadsada2323",
    fuel_type: "Petrol",
    transmission: "Manual",
    extra_fittings: "yes",
    tax_valid: "2024-09-01",
    total_km_driven: "12000",
    vehicle_registration_number: "UP12EF7890",
    published: "yes",
    sold: "no",
    description: "Classic Mustang with a modern twist",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price: "5000000",
    thumbnail: "porschecar.png",
  },
];

export const customers = [
  {
    user_id: 104,
    Full_Name: "Varsha",
    Email_address: "ammuvarsha37@gmail.com",
    Password: "$2b$10$05pkm0cX/eeHrRiE2YkhxuSHiGvQjeGxyKZemFlfC7cldG43jINO6",
    Dob: "2000-03-28",
    isAdmin: "False",
    isStaff: "False",
    Phone_number: 1234567890,
    Address: "",
    isVerified: "True",
    created_date: "2023-03-29 16:04:48",
    last_modified_date: "2023-03-29 16:04:48",
    license_no: "kl121212121212121",
    license_expiry: "2024-01-24",
    aadhar_no: "1212121212121212",
  },
  {
    user_id: 3,
    Full_Name: "CarExpertzUser",
    Email_address: "user@carexpertz.com",
    Password: "$2b$10$E3ECriG9VSYR0XqrOgnWCej3P63lrPwGuGEiw196K8UFqHvKcARq2",
    Dob: "2000-03-28",
    isAdmin: "False",
    isStaff: "False",
    Phone_number: 1234567890,
    Address: "",
    isVerified: "True",
    created_date: "2023-03-29 15:13:34",
    last_modified_date: "2023-03-29 15:13:34",
    license_no: null,
    license_expiry: null,
    aadhar_no: null,
  },
];

export const employees = [
  {
    user_id: 748,
    Full_Name: "Varsha",
    Email_address: "ammuvarsha37222222@gmail.com",
    Password: "$2b$10$oBLae58cA2JJ9T.zBdTOwOKdmnKzOOP4UvtJrwdjXjOWUN50afsYC",
    Dob: "2000-03-28",
    isAdmin: "False",
    isStaff: "True",
    Phone_number: 1234567890,
    Address: "alathur,palakkad",
    isVerified: "True",
    created_date: "2023-04-02 11:50:10",
    last_modified_date: "2023-04-02 11:50:10",
    role: "sales team",
    branch: "Kochi",
    department: "sales",
    empcode: "CX12345",
    no_of_enquires: 5,
  },
  {
    user_id: 749,
    Full_Name: "Varsha",
    Email_address: "ammuvarsha3722222@gmail.com",
    Password: "$2b$10$swlwDHgK9uBc8Riv01hhiuyJ547yUs.YMUdu/vGt2tY1mVVn9YsCy",
    Dob: "0000-00-00",
    isAdmin: "False",
    isStaff: "True",
    Phone_number: 1234567890,
    Address: "palakkad",
    isVerified: "True",
    created_date: "2023-04-02 11:50:10",
    last_modified_date: "2023-04-02 02:53:32",
    role: "sales team",
    branch: "Kochi",
    department: "sales",
    empcode: "CX1235",
    no_of_enquires: 10,
  },
  {
    user_id: 753,
    Full_Name: "Varsha",
    Email_address: "ammuvarsha372222@gmail.com",
    Password: "$2b$10$NhsRXfW6r0jvFKbmwjC6A..RE.Of3Oxmbz4MNTLJFR7nHn2r56yPu",
    Dob: "2000-03-28",
    isAdmin: "False",
    isStaff: "True",
    Phone_number: 1234567890,
    Address: "palakkad",
    isVerified: "True",
    created_date: "2023-04-02 03:06:39",
    last_modified_date: "2023-04-02 03:06:39",
    role: "sales team",
    branch: "Kochi",
    department: "sales",
    empcode: "CX1295",
    no_of_enquires: 2,
  },
];

export const enquires = [
  {
    id: 1,
    Full_Name: "Varsha",
    Email_address: "ammuvarsha37@gmail.com",
    Phone_number: 1234567890,
    Address: "",
    license_no: "kl121212121212121",
    license_expiry: "2024-01-24",
    aadhar_no: "1212121212121212",
    manufacture_name: "Ford",
    model_name: "Mustang",
    model_year: "2021",
    Vehicle_color: "yellow",
    Engine_number: "asdd232123",
    chasis_number: "sadsada2323",
    fuel_type: "Petrol",
    transmission: "Manual",
    vehicle_registration_number: "UP12EF7890",
    assigned_to: "Rahul",
    test_drive_date: "2023-04-10",
    slot_available: "yes",
    test_drive_timeslot: "11am to 1pm",
    current_status: "Processing",
    enquired_date: "2023-03-28",
  },
  {
    id: 2,
    Full_Name: "CarExpertzUser",
    Email_address: "user@carexpertz.com",
    Phone_number: 1234567890,
    Address: "",
    license_no: "kl121212121212121",
    license_expiry: "2024-01-24",
    aadhar_no: "1212121212121212",
    manufacture_name: "Ford",
    model_name: "Mustang",
    model_year: "2021",
    Vehicle_color: "yellow",
    Engine_number: "asdd232123",
    chasis_number: "sadsada2323",
    fuel_type: "Petrol",
    transmission: "Manual",
    vehicle_registration_number: "UP12EF7890",
    assigned_to: "Rahul",
    test_drive_date: "2023-04-10",
    slot_available: "yes",
    test_drive_timeslot: "11am to 1pm",
    current_status: "Purchased",
    enquired_date: "2023-03-28",
  },
  {
    id: 3,
    Full_Name: "Rahul",
    Email_address: "rahul@gmail.com",
    Phone_number: 1234567890,
    Address: "tvm",
    license_no: "kl121212121212121",
    license_expiry: "2024-01-24",
    aadhar_no: "1212121212121212",
    manufacture_name: "Ford",
    model_name: "Mustang",
    model_year: "2021",
    Vehicle_color: "yellow",
    Engine_number: "asdd232123",
    chasis_number: "sadsada2323",
    fuel_type: "Petrol",
    transmission: "Manual",
    vehicle_registration_number: "UP12EF7890",
    assigned_to: "Rahul",
    test_drive_date: "2023-04-10",
    slot_available: "yes",
    test_drive_timeslot: "11am to 1pm",
    current_status: "Completed",
    enquired_date: "2023-03-28",
  },
];
export const sellenquires = [
  {
    id: 1,
    Full_Name: "Varsha",
    Email_address: "ammuvarsha37@gmail.com",
    Phone_number: 1234567890,
    Address: "",
    aadhar_no: "1212121212121212",
    manufacture_name: "Ford",
    model_name: "Mustang",
    model_year: "2021",
    Vehicle_color: "yellow",
    Engine_number: "asdd232123",
    chasis_number: "sadsada2323",
    fuel_type: "Petrol",
    transmission: "Manual",
    vehicle_registration_number: "UP12EF7890",
    assigned_to: "Rahul",
    vehicle_location: "Palakkad",
    extra_fittings: "yes",
    tax_valid: "2024-09-01",
    total_km_driven: "12000",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price_by_customer: "5000000",
    comments_by_customer: "Have Bent on rear taillight ",
    latest_price_quote: "4000000",
    comments_by_team: "Have bend and color fade issue also",
    vehicle_inspected: "yes",
    status: "purchased",
    created_date: "2023-04-08",
  },
  {
    id: 2,
    Full_Name: "John Doe",
    Email_address: "johndoe@gmail.com",
    Phone_number: 9876543210,
    Address: "123 Main St",
    aadhar_no: "3434343434343434",
    manufacture_name: "Toyota",
    model_name: "Camry",
    model_year: "2022",
    Vehicle_color: "silver",
    Engine_number: "asdwe3321",
    chasis_number: "hjgft2233",
    fuel_type: "Petrol",
    transmission: "Automatic",
    vehicle_registration_number: "MH09GV1234",
    assigned_to: "Jane",
    vehicle_location: "Mumbai",
    extra_fittings: "no",
    tax_valid: "2025-01-01",
    total_km_driven: "5000",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price_by_customer: "3500000",
    comments_by_customer: "",
    latest_price_quote: "3000000",
    comments_by_team: "Minor scratch on the rear bumper",
    vehicle_inspected: "yes",
    status: "Cancelled",
    created_date: "2023-04-08",
  },
  {
    id: 3,
    Full_Name: "Sarah Smith",
    Email_address: "sarahsmith@gmail.com",
    Phone_number: 4567891230,
    Address: "456 Oak St",
    aadhar_no: "8787878787878787",
    manufacture_name: "Chevrolet",
    model_name: "Corvette",
    model_year: "2023",
    Vehicle_color: "red",
    Engine_number: "tyrtu9845",
    chasis_number: "ghfth6789",
    fuel_type: "Diesel",
    transmission: "Manual",
    vehicle_registration_number: "TX23JK5678",
    assigned_to: "",
    vehicle_location: "Houston",
    extra_fittings: "yes",
    tax_valid: "2024-12-31",
    total_km_driven: "1500",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price_by_customer: "8000000",
    comments_by_customer: "Needs new tires",
    latest_price_quote: "7500000",
    comments_by_team: "",
    vehicle_inspected: "yes",
    status: "Processing",
    created_date: "2023-04-08",
  },
  {
    id: 4,
    Full_Name: "John Smith",
    Email_address: "johnsmith@example.com",
    Phone_number: 9876543210,
    Address: "123 Main St",
    aadhar_no: "3434343434343434",
    manufacture_name: "Toyota",
    model_name: "Camry",
    model_year: "2019",
    Vehicle_color: "silver",
    Engine_number: "qwe123qwe",
    chasis_number: "zxc456zxc",
    fuel_type: "Diesel",
    transmission: "Automatic",
    vehicle_registration_number: "CA3456DE",
    assigned_to: "Jessica",
    vehicle_location: "San Francisco",
    extra_fittings: "no",
    tax_valid: "2025-05-12",
    total_km_driven: "32000",
    front_view_image: "demo_car_baleno_front_view.jpg",
    rear_left_view_image: "demo_car_baleno_rear_left_view.jpg",
    rear_view_image: "demo_car_baleno_rear_view.jpg",
    left_side_image: "demo_car_baleno_left_view.jpg",
    rc_book_image: "demo_rc_book.png",
    pucc_image: "demo_pucc.png",
    price_by_customer: "27000",
    comments_by_customer: "Minor scratch on front bumper",
    latest_price_quote: "25000",
    comments_by_team: "Needs new tires, windshield crack",
    vehicle_inspected: "yes",
    status: "Processing",
    created_date: "2023-04-08",
  },
];
